feat: Add language search option
DiamondMiner88/nhentai pull request #10
Opened 2021-08-13 14:54 UTC by TurboCheetah

2021-08-13 17:05 UTC, DiamondMiner88 commented
How does this exactly work?
It looks like it just merges query + language
I am unaware of a `language` query param.

2021-08-13 17:30 UTC, TurboCheetah commented
That is all it's doing. I just happened to notice adding it to the end of a search query returned only results in that language. Since I found that through luck I felt that adding a language option would be more straightforward to a user who may not think it's easily possible to filter by language.

2021-08-13 23:15 UTC, DiamondMiner88 requested changes

2021-08-13 23:15 UTC, DiamondMiner88 commented on src/api.ts
> +    doujinExists(id: number): Promise<boolean> {
I made methods accepting an ID use `number | string` to reduce duplicated code. Why would you change this?

2021-08-13 23:15 UTC, DiamondMiner88 commented on src/api.ts
> +        const res = await this.fetch(`/galleries/search?query=${query}${options.language ? ` ${options.language}` : ''}&page=${options.page ? `${options.page}` : 1}&sort=${options.sort ? `${options.s
```suggestion
        const res = await this.fetch(`/galleries/search?query=${query}${options.language ? ` ${options.language}` : ''}&page=${options.page || '1'}&sort=${options.sort || SortMethods.RECENT}`);
```

2021-08-13 23:15 UTC, DiamondMiner88 commented on src/api.ts
> -        if (!SortValues.includes(sort)) throw new TypeError('sort method is not valid');
Why remove argument type checking on all methods? Especially when you pass an invalid `sort` param here it returns an api error thats nearly impossible to debug.

2021-08-13 23:15 UTC, DiamondMiner88 commented on src/api.ts
> +        const res = await this.fetch(`/galleries/tagged?tag_id=${id}&page=${options.page ? `${options.page}` : 1}${options.sort ? `&sort=${options.sort}` : ''}`);
```suggestion
        const res = await this.fetch(`/galleries/tagged?tag_id=${id}&page=${options.page || '1'}${options.sort ? `&sort=${options.sort}` : ''}`);
```

2021-08-13 23:15 UTC, DiamondMiner88 commented on src/apitypes.ts
> +export interface APISearchOptions {
This doesn't belong here, since its not strictly API because of the `language` property. Moving this to `api.ts` would be better.

2021-08-21 01:37 UTC, DiamondMiner88 approved these changes

2021-08-21 01:51 UTC, merged